/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libs.uilib;

import dbcon.DBConnection;
import dbcon.MySQLConnection;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import libs.funclib.ConvertToIcons;
import libs.funclib.Nullify;

/**
 *
 * @author Nicolas
 */
public class Main extends javax.swing.JFrame implements Nullify{
    private ConvertToIcons setIcons;   
    
   
    /**
     * Creates new form main
     */
    public Main() {
        System.gc();
        initComponents();
        setIcons = new ConvertToIcons();
        //calling icon-resizing functions
        setIcons.getUserIcon(label_reg_user);
        setIcons.getBookIcon(label_reg_book);
        setIcons.getStaffIcon(label_reg_staff);
        setIcons.getIssueBookIcon(label_issue_book);
        setIcons.getReturnBookIcon(label_return_book);
        setIcons.getLogoutIcon(label_logout);       
        //disables window resizing and centers the window
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);        
        //
        this.getContentPane().setBackground(Color.WHITE);
        //this.panel_top.setBackground(Color.BLACK);
        
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_reg_staff = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_logout = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label_reg_user = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        label_issue_book = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_return_book = new javax.swing.JLabel();
        label_reg_book = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Bibliotecario");
        setBounds(new java.awt.Rectangle(0, 0, 1024, 768));

        label_reg_staff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_reg_staff.setToolTipText("Registro del personal y de sus funciones.");
        label_reg_staff.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        label_reg_staff.setFocusable(false);
        label_reg_staff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_reg_staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_reg_staffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_reg_staffMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_reg_staffMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel3.setText("Gestionar  Personal");

        label_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_logout.setToolTipText("Desconectarse del servidor y regresar a la ventana de autenticación.");
        label_logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_logout.setMaximumSize(new java.awt.Dimension(88, 14));
        label_logout.setMinimumSize(new java.awt.Dimension(88, 14));
        label_logout.setPreferredSize(new java.awt.Dimension(88, 14));
        label_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_logoutMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel7.setText("Desconectarse");

        label_reg_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_reg_user.setToolTipText("Registro de los estudiantes y usuarios en general.");
        label_reg_user.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_reg_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_reg_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_reg_userMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_reg_userMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel1.setText("Gestionar  Usuarios");

        label_issue_book.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_issue_book.setToolTipText("Gestiona y registra los préstamos.");
        label_issue_book.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_issue_book.setMaximumSize(new java.awt.Dimension(88, 14));
        label_issue_book.setMinimumSize(new java.awt.Dimension(88, 14));
        label_issue_book.setPreferredSize(new java.awt.Dimension(88, 14));
        label_issue_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_issue_bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_issue_bookMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_issue_bookMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel4.setText("Préstamos");

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel6.setText("Devoluciones");

        label_return_book.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_return_book.setToolTipText("Gestiona y registra las devoluciones.");
        label_return_book.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_return_book.setMaximumSize(new java.awt.Dimension(88, 14));
        label_return_book.setMinimumSize(new java.awt.Dimension(88, 14));
        label_return_book.setPreferredSize(new java.awt.Dimension(88, 14));
        label_return_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_return_bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_return_bookMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_return_bookMousePressed(evt);
            }
        });

        label_reg_book.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_reg_book.setToolTipText("Gestionamiento de libros. Al entrar puede escoger entre añadir libros a la biblioteca o removerlos.");
        label_reg_book.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_reg_book.setMaximumSize(new java.awt.Dimension(88, 14));
        label_reg_book.setMinimumSize(new java.awt.Dimension(88, 14));
        label_reg_book.setPreferredSize(new java.awt.Dimension(88, 14));
        label_reg_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_reg_bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_reg_bookMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_reg_bookMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel2.setText("Gestionar Libros");

        jPanel1.setBackground(new java.awt.Color(65, 65, 65));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_reg_user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addComponent(label_reg_book, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(label_reg_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(label_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(label_return_book, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(32, 32, 32)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_issue_book, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel4)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_reg_user, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_reg_book, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_reg_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)))
                    .addComponent(label_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_return_book, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_issue_book, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Mouse Events.
    private void label_reg_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_reg_userMouseEntered
        label_reg_user.setOpaque(true);
        label_reg_user.setBackground(new Color(181,230,29));
        label_reg_user.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_reg_userMouseEntered

    private void label_reg_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_reg_userMouseExited
        label_reg_user.setOpaque(true);
        label_reg_user.setBackground(Color.WHITE);
        label_reg_user.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_reg_userMouseExited

    private void label_reg_bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_reg_bookMouseEntered
        label_reg_book.setOpaque(true);
        label_reg_book.setBackground(new Color(181,230,29));
        label_reg_book.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_reg_bookMouseEntered

    private void label_reg_bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_reg_bookMouseExited
        label_reg_book.setOpaque(true);
        label_reg_book.setBackground(Color.WHITE);
        label_reg_book.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_reg_bookMouseExited

    private void label_reg_staffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_reg_staffMouseEntered
        label_reg_staff.setOpaque(true);
        label_reg_staff.setBackground(new Color(181,230,29));
        label_reg_staff.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_reg_staffMouseEntered

    private void label_reg_staffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_reg_staffMouseExited
        label_reg_staff.setOpaque(true);
        label_reg_staff.setBackground(Color.WHITE);
        label_reg_staff.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_reg_staffMouseExited

    private void label_return_bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_return_bookMouseEntered
        label_return_book.setOpaque(true);
        label_return_book.setBackground(new Color(181,230,29));
        label_return_book.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_return_bookMouseEntered

    private void label_return_bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_return_bookMouseExited
        label_return_book.setOpaque(true);
        label_return_book.setBackground(Color.WHITE);
        label_return_book.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_return_bookMouseExited

    private void label_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_logoutMouseEntered
        label_logout.setOpaque(true);
        label_logout.setBackground(new Color(181,230,29));
        label_logout.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_logoutMouseEntered

    private void label_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_logoutMouseExited
        label_logout.setOpaque(true);
        label_logout.setBackground(Color.WHITE);
        label_logout.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_logoutMouseExited

    private void label_issue_bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_issue_bookMouseExited
        label_issue_book.setOpaque(true);
        label_issue_book.setBackground(Color.WHITE);
        label_issue_book.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_issue_bookMouseExited

    private void label_issue_bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_issue_bookMouseEntered
        label_issue_book.setOpaque(true);
        label_issue_book.setBackground(new Color(181,230,29));
        label_issue_book.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_issue_bookMouseEntered

    private void label_reg_staffMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_reg_staffMousePressed
         new ManageStaff().setVisible(true);
         this.disposeOfAll();
         this.dispose();
         System.gc();
         
    }//GEN-LAST:event_label_reg_staffMousePressed

    private void label_reg_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_reg_userMousePressed
        new ManageUsers().setVisible(true);
        disposeOfAll();
        this.dispose();
        System.gc();
    }//GEN-LAST:event_label_reg_userMousePressed

    private void label_reg_bookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_reg_bookMousePressed
        new ManageBooks().setVisible(true);
        this.disposeOfAll();
        this.dispose();        
        System.gc();
    }//GEN-LAST:event_label_reg_bookMousePressed

    private void label_return_bookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_return_bookMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_return_bookMousePressed

    private void label_issue_bookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_issue_bookMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_issue_bookMousePressed

    private void label_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_logoutMouseClicked
        this.disposeOfAll();
        this.dispose();        
        /*DBConnection con = new MySQLConnection();
        try {
            ((MySQLConnection)con).getCon().close();
            
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } */
        System.gc();
        new Login().setVisible(true);
    }//GEN-LAST:event_label_logoutMouseClicked
    //End of.
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_issue_book;
    private javax.swing.JLabel label_logout;
    private javax.swing.JLabel label_reg_book;
    private javax.swing.JLabel label_reg_staff;
    private javax.swing.JLabel label_reg_user;
    private javax.swing.JLabel label_return_book;
    // End of variables declaration//GEN-END:variables


    @Override
    public void disposeOfAll(){
         this.jLabel1 = null;
         this.jLabel2 = null;
         this.jLabel3 = null;
         this.jLabel4 = null;
         this.jLabel6 = null;
         this.jLabel7 = null;
         this.label_logout = null;
         this.label_issue_book = null;
         this.label_reg_book = null;
         this.label_reg_staff = null;
         this.label_reg_user = null;
         this.label_return_book = null;
         this.rootPane = null;         
    }   

}
