/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libs.uilib;

import java.awt.Color;
import libs.funclib.ConvertToIcons;
import libs.funclib.KeyEvents;
import libs.funclib.Nullify;

/**
 *
 * @author Nicolas
 */
public class ManageBooks extends javax.swing.JFrame implements Nullify{
    
    
    private KeyEvents restrict;
    private ConvertToIcons setIcons;
    /**
     * Creates new form ManageBooks
     */
    public ManageBooks() {
        System.gc();
        initComponents();
        setIcons = new ConvertToIcons();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.panel_func.setBackground(Color.WHITE);
        this.panel_add_book.setBackground(Color.WHITE);
        this.panel_search_book.setBackground(Color.WHITE);
        this.panel_main.setBackground(Color.WHITE);
        
        setIcons.getExitIcon(label_exit);
        setIcons.getReturnHomeIcon(label_home);
        setIcons.getAddBookIcon(label_add_book);
        setIcons.getSearchBookIcon(label_search_book);
        restrict = new KeyEvents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        panel_options = new javax.swing.JPanel();
        label_home = new javax.swing.JLabel();
        label_exit = new javax.swing.JLabel();
        label_search_book = new javax.swing.JLabel();
        label_add_book = new javax.swing.JLabel();
        panel_func = new javax.swing.JPanel();
        panel_add_book = new javax.swing.JPanel();
        panel_top1_text = new javax.swing.JPanel();
        label_top_panel1 = new javax.swing.JLabel();
        txt_add_book_title = new javax.swing.JTextField();
        label_add_book_code = new javax.swing.JLabel();
        label_add_book_title = new javax.swing.JLabel();
        txt_add_book_code = new javax.swing.JTextField();
        label_add_book_edition = new javax.swing.JLabel();
        txt_add_book_author = new javax.swing.JTextField();
        txt_add_book_edition = new javax.swing.JTextField();
        txt_add_book_price = new javax.swing.JTextField();
        label_add_book_author = new javax.swing.JLabel();
        cmb_add_book_type = new javax.swing.JComboBox<>();
        label_add_book_type = new javax.swing.JLabel();
        txt_add_book_isbn = new javax.swing.JTextField();
        label_add_book_isbn = new javax.swing.JLabel();
        label_add_book_price = new javax.swing.JLabel();
        label_add_num_pages = new javax.swing.JLabel();
        txt_add_num_pages = new javax.swing.JTextField();
        label_add_publisher = new javax.swing.JLabel();
        txt_add_publisher = new javax.swing.JTextField();
        label_add_publisher_email = new javax.swing.JLabel();
        txt_add_publisher_email = new javax.swing.JTextField();
        label_add_publisher_address = new javax.swing.JLabel();
        txt_add_publisher_address = new javax.swing.JTextField();
        label_add_publisher_phone = new javax.swing.JLabel();
        txt_add_publisher_phone = new javax.swing.JTextField();
        panel_search_book = new javax.swing.JPanel();
        panel_top2_text = new javax.swing.JPanel();
        label_top_panel2 = new javax.swing.JLabel();
        label_title = new javax.swing.JLabel();
        txt_search_book_title = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        sc_pane_display_book = new javax.swing.JScrollPane();
        table_display_books = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_main.setBackground(new java.awt.Color(0, 0, 0));
        panel_main.setPreferredSize(new java.awt.Dimension(1024, 408));

        panel_options.setBackground(new java.awt.Color(255, 255, 255));

        label_home.setText("Menú Prinicipal");
        label_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_homeMouseExited(evt);
            }
        });

        label_exit.setText("Salir");
        label_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_exitMouseExited(evt);
            }
        });

        label_search_book.setText("Buscar");
        label_search_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_search_bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_search_bookMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_search_bookMousePressed(evt);
            }
        });

        label_add_book.setText("Añadir");
        label_add_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_add_bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_add_bookMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_add_bookMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel_optionsLayout = new javax.swing.GroupLayout(panel_options);
        panel_options.setLayout(panel_optionsLayout);
        panel_optionsLayout.setHorizontalGroup(
            panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_optionsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_home, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_search_book, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_add_book, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panel_optionsLayout.setVerticalGroup(
            panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_optionsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(label_add_book, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_search_book, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_home, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_func.setBackground(new java.awt.Color(255, 255, 255));
        panel_func.setLayout(new java.awt.CardLayout());

        panel_top1_text.setBackground(new java.awt.Color(65, 65, 65));

        label_top_panel1.setBackground(new java.awt.Color(255, 255, 255));
        label_top_panel1.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        label_top_panel1.setForeground(new java.awt.Color(255, 255, 255));
        label_top_panel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_top_panel1.setText("GESTIONAMIENTO");
        label_top_panel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_top1_textLayout = new javax.swing.GroupLayout(panel_top1_text);
        panel_top1_text.setLayout(panel_top1_textLayout);
        panel_top1_textLayout.setHorizontalGroup(
            panel_top1_textLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_top_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_top1_textLayout.setVerticalGroup(
            panel_top1_textLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_top1_textLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(label_top_panel1)
                .addGap(29, 29, 29))
        );

        txt_add_book_title.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        label_add_book_code.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_book_code.setText("Código del libro");

        label_add_book_title.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_book_title.setText("Título del libro");

        txt_add_book_code.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txt_add_book_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_add_book_codeKeyTyped(evt);
            }
        });

        label_add_book_edition.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_book_edition.setText("Edición");

        txt_add_book_author.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        txt_add_book_edition.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txt_add_book_edition.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_add_book_editionKeyTyped(evt);
            }
        });

        txt_add_book_price.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txt_add_book_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_add_book_priceKeyTyped(evt);
            }
        });

        label_add_book_author.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_book_author.setText("Autor del libro");

        cmb_add_book_type.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        cmb_add_book_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione una opción>...", "Autobiografía", "Biografía", "Científico", "De viaje", "De referencia/consulta", "Literatura y lingüístico", "Libro de texto", "Monografía", "Poético", "Recreativo" }));

        label_add_book_type.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_book_type.setText("Tipo de libro");

        txt_add_book_isbn.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txt_add_book_isbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_add_book_isbnKeyTyped(evt);
            }
        });

        label_add_book_isbn.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_book_isbn.setText("ISBN");

        label_add_book_price.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_book_price.setText("Precio");

        label_add_num_pages.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_num_pages.setText("Número de páginas");

        txt_add_num_pages.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txt_add_num_pages.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_add_num_pagesKeyTyped(evt);
            }
        });

        label_add_publisher.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_publisher.setText("Editorial");

        txt_add_publisher.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        label_add_publisher_email.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_publisher_email.setText("e-mail de editorial");

        txt_add_publisher_email.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        label_add_publisher_address.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_publisher_address.setText("Dirección");

        txt_add_publisher_address.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        label_add_publisher_phone.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_publisher_phone.setText("Teléfono");

        txt_add_publisher_phone.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txt_add_publisher_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_add_publisher_phoneKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panel_add_bookLayout = new javax.swing.GroupLayout(panel_add_book);
        panel_add_book.setLayout(panel_add_bookLayout);
        panel_add_bookLayout.setHorizontalGroup(
            panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_top1_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_add_bookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_add_book_code)
                    .addComponent(label_add_book_title)
                    .addComponent(label_add_book_author)
                    .addComponent(label_add_book_edition)
                    .addComponent(label_add_book_type)
                    .addComponent(label_add_book_isbn)
                    .addComponent(label_add_num_pages)
                    .addComponent(label_add_book_price))
                .addGap(59, 59, 59)
                .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_add_book_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_add_book_type, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_add_num_pages, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_add_book_price, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_add_bookLayout.createSequentialGroup()
                        .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_add_book_title, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txt_add_book_author, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txt_add_book_edition, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txt_add_book_code))
                        .addGap(26, 26, 26)
                        .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_add_publisher_phone)
                            .addGroup(panel_add_bookLayout.createSequentialGroup()
                                .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_add_publisher)
                                    .addComponent(label_add_publisher_email))
                                .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_add_bookLayout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(txt_add_publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_add_bookLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_add_publisher_address, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                            .addComponent(txt_add_publisher_email, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                            .addComponent(txt_add_publisher_phone)))))
                            .addComponent(label_add_publisher_address))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_add_bookLayout.setVerticalGroup(
            panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_add_bookLayout.createSequentialGroup()
                .addComponent(panel_top1_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_add_bookLayout.createSequentialGroup()
                        .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_add_book_code)
                            .addComponent(txt_add_book_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_add_book_title)
                            .addComponent(txt_add_book_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_add_publisher_email)
                            .addComponent(txt_add_publisher_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_add_book_author)
                            .addComponent(txt_add_book_author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_add_publisher_address)
                            .addComponent(txt_add_publisher_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_add_publisher)
                        .addComponent(txt_add_publisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_add_publisher_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_add_book_edition)
                        .addComponent(txt_add_book_edition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_add_publisher_phone)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_add_book_type)
                    .addComponent(cmb_add_book_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_add_book_isbn)
                    .addComponent(txt_add_book_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_add_num_pages)
                    .addComponent(txt_add_num_pages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_add_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_add_book_price)
                    .addComponent(txt_add_book_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panel_func.add(panel_add_book, "card2");

        panel_top2_text.setBackground(new java.awt.Color(65, 65, 65));

        label_top_panel2.setBackground(new java.awt.Color(255, 255, 255));
        label_top_panel2.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        label_top_panel2.setForeground(new java.awt.Color(255, 255, 255));
        label_top_panel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_top_panel2.setText("BÚSQUEDA");
        label_top_panel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_top2_textLayout = new javax.swing.GroupLayout(panel_top2_text);
        panel_top2_text.setLayout(panel_top2_textLayout);
        panel_top2_textLayout.setHorizontalGroup(
            panel_top2_textLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_top_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_top2_textLayout.setVerticalGroup(
            panel_top2_textLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_top2_textLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(label_top_panel2)
                .addGap(29, 29, 29))
        );

        label_title.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_title.setText("Título");

        txt_search_book_title.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        btn_search.setBackground(new java.awt.Color(255, 255, 255));
        btn_search.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btn_search.setText("OK");

        table_display_books.setAutoCreateRowSorter(true);
        table_display_books.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        table_display_books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "ISBN", "Título", "Autor", "Edición", "Tipo", "Editorial", "Dirección", "Disponibilidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sc_pane_display_book.setViewportView(table_display_books);

        javax.swing.GroupLayout panel_search_bookLayout = new javax.swing.GroupLayout(panel_search_book);
        panel_search_book.setLayout(panel_search_bookLayout);
        panel_search_bookLayout.setHorizontalGroup(
            panel_search_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_top2_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_search_bookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sc_pane_display_book, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE))
            .addGroup(panel_search_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_search_bookLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(label_title)
                    .addGap(32, 32, 32)
                    .addComponent(txt_search_book_title, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(465, Short.MAX_VALUE)))
        );
        panel_search_bookLayout.setVerticalGroup(
            panel_search_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_search_bookLayout.createSequentialGroup()
                .addComponent(panel_top2_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(sc_pane_display_book, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 126, Short.MAX_VALUE))
            .addGroup(panel_search_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_search_bookLayout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addGroup(panel_search_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_title)
                        .addComponent(txt_search_book_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_search))
                    .addContainerGap(238, Short.MAX_VALUE)))
        );

        panel_func.add(panel_search_book, "card3");

        javax.swing.GroupLayout panel_mainLayout = new javax.swing.GroupLayout(panel_main);
        panel_main.setLayout(panel_mainLayout);
        panel_mainLayout.setHorizontalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_func, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_mainLayout.setVerticalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_func, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_add_book_codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_book_codeKeyTyped
        restrict.onlyNumeric(evt);
    }//GEN-LAST:event_txt_add_book_codeKeyTyped

    private void txt_add_book_editionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_book_editionKeyTyped
        restrict.onlyNumeric(evt);
    }//GEN-LAST:event_txt_add_book_editionKeyTyped

    private void txt_add_book_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_book_priceKeyTyped
        restrict.onlyAlphabetic(evt);
    }//GEN-LAST:event_txt_add_book_priceKeyTyped

    private void txt_add_book_isbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_book_isbnKeyTyped
        restrict.onlyNumeric(evt);
    }//GEN-LAST:event_txt_add_book_isbnKeyTyped

    private void txt_add_num_pagesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_num_pagesKeyTyped
        restrict.onlyNumeric(evt);
    }//GEN-LAST:event_txt_add_num_pagesKeyTyped

    private void txt_add_publisher_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_publisher_phoneKeyTyped
        restrict.onlyNumeric(evt);
    }//GEN-LAST:event_txt_add_publisher_phoneKeyTyped

    private void label_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_homeMouseClicked
        new Main().setVisible(true);
        this.disposeOfAll();
        this.dispose();
    }//GEN-LAST:event_label_homeMouseClicked

    private void label_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_homeMouseEntered
        label_home.setOpaque(true);
        label_home.setBackground(new Color(181,230,29));
        label_home.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_homeMouseEntered

    private void label_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_homeMouseExited
        label_home.setOpaque(true);
        label_home.setBackground(Color.WHITE);
        label_home.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_homeMouseExited

    private void label_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseClicked
        this.disposeOfAll();
        this.dispose();
    }//GEN-LAST:event_label_exitMouseClicked

    private void label_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseEntered
        label_exit.setOpaque(true);
        label_exit.setBackground(new Color(181,230,29));
        label_exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_exitMouseEntered

    private void label_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseExited
        label_exit.setOpaque(true);
        label_exit.setBackground(Color.WHITE);
        label_exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_exitMouseExited

    private void label_search_bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_search_bookMouseEntered
        label_search_book.setOpaque(true);
        label_search_book.setBackground(new Color(181,230,29));
        label_search_book.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_search_bookMouseEntered

    private void label_search_bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_search_bookMouseExited
        label_search_book.setOpaque(true);
        label_search_book.setBackground(Color.WHITE);
        label_search_book.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_search_bookMouseExited

    private void label_search_bookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_search_bookMousePressed
        // TODO add your handling code here:
        this.panel_func.removeAll();
        this.panel_func.repaint();
        this.panel_func.revalidate();
        this.panel_func.add(this.panel_search_book);
        this.panel_func.repaint();
        this.panel_func.revalidate();
    }//GEN-LAST:event_label_search_bookMousePressed

    private void label_add_bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_add_bookMouseEntered
        label_add_book.setOpaque(true);
        label_add_book.setBackground(new Color(181,230,29));
        label_add_book.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_add_bookMouseEntered

    private void label_add_bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_add_bookMouseExited
        label_add_book.setOpaque(true);
        label_add_book.setBackground(Color.WHITE);
        label_add_book.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_add_bookMouseExited

    private void label_add_bookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_add_bookMousePressed
        // TODO add your handling code here:
        this.panel_func.removeAll();
        this.panel_func.repaint();
        this.panel_func.revalidate();
        this.panel_func.add(this.panel_add_book);
        this.panel_func.repaint();
        this.panel_func.revalidate();
    }//GEN-LAST:event_label_add_bookMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox<String> cmb_add_book_type;
    private javax.swing.JLabel label_add_book;
    private javax.swing.JLabel label_add_book_author;
    private javax.swing.JLabel label_add_book_code;
    private javax.swing.JLabel label_add_book_edition;
    private javax.swing.JLabel label_add_book_isbn;
    private javax.swing.JLabel label_add_book_price;
    private javax.swing.JLabel label_add_book_title;
    private javax.swing.JLabel label_add_book_type;
    private javax.swing.JLabel label_add_num_pages;
    private javax.swing.JLabel label_add_publisher;
    private javax.swing.JLabel label_add_publisher_address;
    private javax.swing.JLabel label_add_publisher_email;
    private javax.swing.JLabel label_add_publisher_phone;
    private javax.swing.JLabel label_exit;
    private javax.swing.JLabel label_home;
    private javax.swing.JLabel label_search_book;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel label_top_panel1;
    private javax.swing.JLabel label_top_panel2;
    private javax.swing.JPanel panel_add_book;
    private javax.swing.JPanel panel_func;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_options;
    private javax.swing.JPanel panel_search_book;
    private javax.swing.JPanel panel_top1_text;
    private javax.swing.JPanel panel_top2_text;
    private javax.swing.JScrollPane sc_pane_display_book;
    private javax.swing.JTable table_display_books;
    private javax.swing.JTextField txt_add_book_author;
    private javax.swing.JTextField txt_add_book_code;
    private javax.swing.JTextField txt_add_book_edition;
    private javax.swing.JTextField txt_add_book_isbn;
    private javax.swing.JTextField txt_add_book_price;
    private javax.swing.JTextField txt_add_book_title;
    private javax.swing.JTextField txt_add_num_pages;
    private javax.swing.JTextField txt_add_publisher;
    private javax.swing.JTextField txt_add_publisher_address;
    private javax.swing.JTextField txt_add_publisher_email;
    private javax.swing.JTextField txt_add_publisher_phone;
    private javax.swing.JTextField txt_search_book_title;
    // End of variables declaration//GEN-END:variables


    @Override
    public void disposeOfAll() {
        this.label_top_panel2 = null;
        this.label_top_panel1 = null;
        this.panel_top1_text = null;
        this.panel_top2_text = null;
        this.label_add_book = null;
        this.label_exit = null;
        this.label_home = null;
        this.label_search_book = null;
        this.panel_func = null;
        this.panel_add_book = null;
        this.panel_main = null;
        this.panel_options = null;
        this.panel_search_book = null;
        this.rootPane = null;
    }

    
}
