/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libs.uilib;

import java.awt.Color;
import libs.funclib.ConvertToIcons;
import libs.funclib.KeyEvents;
import libs.funclib.Nullify;

/**
 *
 * @author Nicolas
 */
public class ManageStaff extends javax.swing.JFrame implements Nullify{
    private KeyEvents restrict;
    private ConvertToIcons setIcons;
    /**
     * Creates new form ManageStaff
     */
    public ManageStaff() {
        System.gc();
        initComponents();
        restrict = new KeyEvents();
        setIcons = new ConvertToIcons();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.panel_func.setBackground(Color.WHITE);
        this.panel_add_staff.setBackground(Color.WHITE);
        this.panel_search_staff.setBackground(Color.WHITE);
        this.panel_main.setBackground(Color.WHITE);
        
        setIcons.getExitIcon(label_exit);
        setIcons.getReturnHomeIcon(label_home);
        setIcons.getAddUserIcon(label_add_user);
        setIcons.getSearchUserIcon(label_search_user);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        panel_options = new javax.swing.JPanel();
        label_add_user = new javax.swing.JLabel();
        label_search_user = new javax.swing.JLabel();
        label_home = new javax.swing.JLabel();
        label_exit = new javax.swing.JLabel();
        panel_func = new javax.swing.JPanel();
        panel_add_staff = new javax.swing.JPanel();
        label_add_id = new javax.swing.JLabel();
        label_add_name = new javax.swing.JLabel();
        label_add_lastname = new javax.swing.JLabel();
        label_add_address = new javax.swing.JLabel();
        label_add_email = new javax.swing.JLabel();
        label_add_post = new javax.swing.JLabel();
        txt_add_id = new javax.swing.JTextField();
        txt_add_name = new javax.swing.JTextField();
        txt_add_lastname = new javax.swing.JTextField();
        txt_add_address = new javax.swing.JTextField();
        txt_add_email = new javax.swing.JTextField();
        txt_add_post = new javax.swing.JTextField();
        panel_top1_text = new javax.swing.JPanel();
        label_top_panel1 = new javax.swing.JLabel();
        panel_search_staff = new javax.swing.JPanel();
        label_search_id = new javax.swing.JLabel();
        txt_search_id = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        panel_top2_text = new javax.swing.JPanel();
        label_top_panel2 = new javax.swing.JLabel();
        sc_pane_display_staff = new javax.swing.JScrollPane();
        table_display_staff = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_main.setBackground(new java.awt.Color(0, 0, 0));
        panel_main.setPreferredSize(new java.awt.Dimension(1024, 408));

        panel_options.setBackground(new java.awt.Color(255, 255, 255));

        label_add_user.setText("Añadir");
        label_add_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_add_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_add_userMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_add_userMousePressed(evt);
            }
        });

        label_search_user.setText("Buscar");
        label_search_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_search_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_search_userMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_search_userMousePressed(evt);
            }
        });

        label_home.setText("Menú Prinicipal");
        label_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_homeMouseExited(evt);
            }
        });

        label_exit.setText("Salir");
        label_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_optionsLayout = new javax.swing.GroupLayout(panel_options);
        panel_options.setLayout(panel_optionsLayout);
        panel_optionsLayout.setHorizontalGroup(
            panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_optionsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_home, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_search_user, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_add_user, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panel_optionsLayout.setVerticalGroup(
            panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_optionsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(label_add_user, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_search_user, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_home, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_func.setBackground(new java.awt.Color(255, 255, 255));
        panel_func.setLayout(new java.awt.CardLayout());

        panel_add_staff.setPreferredSize(new java.awt.Dimension(711, 386));

        label_add_id.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_id.setText("Cédula");

        label_add_name.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_name.setText("Nombres");

        label_add_lastname.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_lastname.setText("Apellidos");

        label_add_address.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_address.setText("Dirección");

        label_add_email.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_email.setText("e-mail");

        label_add_post.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_add_post.setText("Cargo");

        txt_add_id.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txt_add_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_add_idKeyTyped(evt);
            }
        });

        txt_add_name.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txt_add_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_add_nameKeyTyped(evt);
            }
        });

        txt_add_lastname.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txt_add_lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_add_lastnameKeyTyped(evt);
            }
        });

        txt_add_address.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        txt_add_email.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        txt_add_post.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        panel_top1_text.setBackground(new java.awt.Color(65, 65, 65));

        label_top_panel1.setBackground(new java.awt.Color(255, 255, 255));
        label_top_panel1.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        label_top_panel1.setForeground(new java.awt.Color(255, 255, 255));
        label_top_panel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_top_panel1.setText("REGISTRO DE PERSONAL");
        label_top_panel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_top1_textLayout = new javax.swing.GroupLayout(panel_top1_text);
        panel_top1_text.setLayout(panel_top1_textLayout);
        panel_top1_textLayout.setHorizontalGroup(
            panel_top1_textLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_top_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_top1_textLayout.setVerticalGroup(
            panel_top1_textLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_top1_textLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(label_top_panel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_add_staffLayout = new javax.swing.GroupLayout(panel_add_staff);
        panel_add_staff.setLayout(panel_add_staffLayout);
        panel_add_staffLayout.setHorizontalGroup(
            panel_add_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_add_staffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_add_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_add_id)
                    .addComponent(label_add_name)
                    .addComponent(label_add_lastname)
                    .addComponent(label_add_address)
                    .addComponent(label_add_email)
                    .addComponent(label_add_post))
                .addGap(29, 29, 29)
                .addGroup(panel_add_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_add_post, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(txt_add_email)
                    .addComponent(txt_add_id)
                    .addComponent(txt_add_name)
                    .addComponent(txt_add_lastname)
                    .addComponent(txt_add_address))
                .addContainerGap(560, Short.MAX_VALUE))
            .addComponent(panel_top1_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_add_staffLayout.setVerticalGroup(
            panel_add_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_add_staffLayout.createSequentialGroup()
                .addComponent(panel_top1_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panel_add_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_add_id)
                    .addComponent(txt_add_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_add_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_add_name)
                    .addComponent(txt_add_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_add_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_add_lastname)
                    .addComponent(txt_add_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_add_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_add_address)
                    .addComponent(txt_add_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_add_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_add_email)
                    .addComponent(txt_add_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_add_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_add_post)
                    .addComponent(txt_add_post, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        panel_func.add(panel_add_staff, "card2");

        panel_search_staff.setBackground(new java.awt.Color(255, 255, 255));

        label_search_id.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label_search_id.setText("Cédula");

        txt_search_id.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        btn_search.setBackground(new java.awt.Color(255, 255, 255));
        btn_search.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btn_search.setText("OK");

        panel_top2_text.setBackground(new java.awt.Color(65, 65, 65));

        label_top_panel2.setBackground(new java.awt.Color(255, 255, 255));
        label_top_panel2.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        label_top_panel2.setForeground(new java.awt.Color(255, 255, 255));
        label_top_panel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_top_panel2.setText("BÚSQUEDA");
        label_top_panel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_top2_textLayout = new javax.swing.GroupLayout(panel_top2_text);
        panel_top2_text.setLayout(panel_top2_textLayout);
        panel_top2_textLayout.setHorizontalGroup(
            panel_top2_textLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_top_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_top2_textLayout.setVerticalGroup(
            panel_top2_textLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_top2_textLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(label_top_panel2)
                .addGap(29, 29, 29))
        );

        table_display_staff.setAutoCreateRowSorter(true);
        table_display_staff.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        table_display_staff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombres", "Apellidos", "Cargo", "Dirección", "e-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sc_pane_display_staff.setViewportView(table_display_staff);

        javax.swing.GroupLayout panel_search_staffLayout = new javax.swing.GroupLayout(panel_search_staff);
        panel_search_staff.setLayout(panel_search_staffLayout);
        panel_search_staffLayout.setHorizontalGroup(
            panel_search_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_search_staffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_search_id)
                .addGap(32, 32, 32)
                .addComponent(txt_search_id, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(465, Short.MAX_VALUE))
            .addComponent(sc_pane_display_staff, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(panel_top2_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_search_staffLayout.setVerticalGroup(
            panel_search_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_search_staffLayout.createSequentialGroup()
                .addComponent(panel_top2_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panel_search_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_search_id)
                    .addComponent(txt_search_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search))
                .addGap(18, 18, 18)
                .addComponent(sc_pane_display_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        panel_func.add(panel_search_staff, "card2");

        javax.swing.GroupLayout panel_mainLayout = new javax.swing.GroupLayout(panel_main);
        panel_main.setLayout(panel_mainLayout);
        panel_mainLayout.setHorizontalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_func, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_mainLayout.setVerticalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_func, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_mainLayout.createSequentialGroup()
                        .addComponent(panel_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_add_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_add_userMouseEntered
        label_add_user.setOpaque(true);
        label_add_user.setBackground(new Color(181,230,29));
        label_add_user.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_add_userMouseEntered

    private void label_add_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_add_userMouseExited
        label_add_user.setOpaque(true);
        label_add_user.setBackground(Color.WHITE);
        label_add_user.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_add_userMouseExited

    private void label_add_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_add_userMousePressed
        // TODO add your handling code here:
        this.panel_func.removeAll();
        this.panel_func.repaint();
        this.panel_func.revalidate();
        this.panel_func.add(this.panel_add_staff);
        this.panel_func.repaint();
        this.panel_func.revalidate();
    }//GEN-LAST:event_label_add_userMousePressed

    private void label_search_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_search_userMouseEntered
        label_search_user.setOpaque(true);
        label_search_user.setBackground(new Color(181,230,29));
        label_search_user.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_search_userMouseEntered

    private void label_search_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_search_userMouseExited
        label_search_user.setOpaque(true);
        label_search_user.setBackground(Color.WHITE);
        label_search_user.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_search_userMouseExited

    private void label_search_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_search_userMousePressed
        // TODO add your handling code here:
        this.panel_func.removeAll();
        this.panel_func.repaint();
        this.panel_func.revalidate();
        this.panel_func.add(this.panel_search_staff);
        this.panel_func.repaint();
        this.panel_func.revalidate();
    }//GEN-LAST:event_label_search_userMousePressed

    private void label_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_homeMouseEntered
        label_home.setOpaque(true);
        label_home.setBackground(new Color(181,230,29));
        label_home.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_homeMouseEntered

    private void label_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_homeMouseExited
        label_home.setOpaque(true);
        label_home.setBackground(Color.WHITE);
        label_home.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_homeMouseExited

    private void label_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseEntered
        label_exit.setOpaque(true);
        label_exit.setBackground(new Color(181,230,29));
        label_exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_exitMouseEntered

    private void label_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseExited
        label_exit.setOpaque(true);
        label_exit.setBackground(Color.WHITE);
        label_exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_label_exitMouseExited

    private void txt_add_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_idKeyTyped
        restrict.onlyNumeric(evt);
    }//GEN-LAST:event_txt_add_idKeyTyped

    private void txt_add_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_nameKeyTyped
        //restrict.onlyAlphabetic(evt);
    }//GEN-LAST:event_txt_add_nameKeyTyped

    private void txt_add_lastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_lastnameKeyTyped
        //restrict.onlyAlphabetic(evt);
    }//GEN-LAST:event_txt_add_lastnameKeyTyped

    private void label_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_homeMouseClicked
        this.disposeOfAll();
        new Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_label_homeMouseClicked

    private void label_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseClicked
        this.disposeOfAll();
        System.exit(0);
    }//GEN-LAST:event_label_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel label_add_address;
    private javax.swing.JLabel label_add_email;
    private javax.swing.JLabel label_add_id;
    private javax.swing.JLabel label_add_lastname;
    private javax.swing.JLabel label_add_name;
    private javax.swing.JLabel label_add_post;
    private javax.swing.JLabel label_add_user;
    private javax.swing.JLabel label_exit;
    private javax.swing.JLabel label_home;
    private javax.swing.JLabel label_search_id;
    private javax.swing.JLabel label_search_user;
    private javax.swing.JLabel label_top_panel1;
    private javax.swing.JLabel label_top_panel2;
    private javax.swing.JPanel panel_add_staff;
    private javax.swing.JPanel panel_func;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_options;
    private javax.swing.JPanel panel_search_staff;
    private javax.swing.JPanel panel_top1_text;
    private javax.swing.JPanel panel_top2_text;
    private javax.swing.JScrollPane sc_pane_display_staff;
    private javax.swing.JTable table_display_staff;
    private javax.swing.JTextField txt_add_address;
    private javax.swing.JTextField txt_add_email;
    private javax.swing.JTextField txt_add_id;
    private javax.swing.JTextField txt_add_lastname;
    private javax.swing.JTextField txt_add_name;
    private javax.swing.JTextField txt_add_post;
    private javax.swing.JTextField txt_search_id;
    // End of variables declaration//GEN-END:variables

 
    @Override
    public void disposeOfAll() {
        this.btn_search = null;
        this.label_add_address = null;
        this.label_add_email = null;
        this.label_add_id = null;
        this.label_add_lastname = null;
        this.label_add_name = null;
        this.label_add_post = null;
        this.label_add_user = null;
        this.label_exit = null;
        this.label_home = null;
        this.label_search_id = null;
        this.label_search_user = null;
        this.label_top_panel1 = null;
        this.label_top_panel2 = null;
        this.panel_add_staff = null;
        this.panel_func = null;
        this.panel_main = null;
        this.panel_options = null;
        this.panel_search_staff = null;
        this.panel_top1_text = null;
        this.panel_top2_text = null;
        this.restrict = null;
        this.rootPane = null;
        this.sc_pane_display_staff = null;
        this.setIcons = null;
        this.table_display_staff = null;
        this.txt_add_address = null;
        this.txt_add_email = null;
        this.txt_add_id = null;
        this.txt_add_lastname = null;
        this.txt_add_name = null;
        this.txt_add_post = null;
        this.txt_search_id = null;
    }
}
